enum ActionTypes {
    ADD_NEW_NOTE = 'NOTES_LIST/ADD_NEW_NOTE',
    ADD_NEW_NOTE_IN_PROGRESS = 'NOTES_LIST/ADD_NEW_NOTE_IN_PROGRESS',
    ADD_NEW_NOTE_COMPLETED = 'NOTES_LIST/ADD_NEW_COMPLETED',
    ADD_NEW_NOTE_FAILED = 'NOTES_LIST/ADD_NEW_NOTE_FAILED',

    OPEN_NOTE = 'NOTES_LIST/OPEN_NOTE',
    OPEN_NOTE_IN_PROGRESS = 'NOTES_LIST/OPEN_NOTE_IN_PROGRESS',
    OPEN_NOTE_COMPLETED = 'NOTES_LIST/OPEN_NOTE_COMPLETED',
    OPEN_NOTE_FAILED = 'NOTES_LIST/OPEN_NOTE_FAILED',

    DELETE_NOTE = 'NOTES_LIST/DELETE_NOTE',
    DELETE_NOTE_IN_PROGRESS = 'NOTES_LIST/DELETE_NOTE',
    DELETE_NOTE_COMPLETED = 'NOTES_LIST/DELETE_NOTE_COMPLETED',
    DELETE_NOTE_FAILED = 'NOTES_LIST/DELETE_NOTE_FAILED',
}

export default ActionTypes;
